apiVersion: extensions/v1beta1
kind: Deployment

metadata:
    name: lua-fuzzing-pod

spec:

    replicas:

    template:

        metadata:

            labels:

                target: lua

        spec:

            containers:

            - name: lua-fuzzer
              image: ouspg/libfuzzer-lua:ops-dev
