apiVersion: extensions/v1beta1
kind: Deployment

metadata:
    name: share-p2p-pod

spec:

    replicas:

    template:

        metadata:

            labels:

        spec:

            containers:

            - name: deluge-node
              image: ouspg/deluge-node:ops-testing
